/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'Safe' : IDL.Null,
  'Emergency' : IDL.Null,
});
export const Location = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addLocation' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Nat], []),
  'deleteLocation' : IDL.Func([IDL.Nat], [], []),
  'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
  'getStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'lastLocation' : IDL.Opt(Location),
          'totalCount' : IDL.Nat,
          'emergencyCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'toggleStatus' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({ 'Safe' : IDL.Null, 'Emergency' : IDL.Null });
  const Location = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addLocation' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Nat], []),
    'deleteLocation' : IDL.Func([IDL.Nat], [], []),
    'getAllLocations' : IDL.Func([], [IDL.Vec(Location)], ['query']),
    'getStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'lastLocation' : IDL.Opt(Location),
            'totalCount' : IDL.Nat,
            'emergencyCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'toggleStatus' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };